title: Yash Kodali
email: yash.kodali@berkeley.edu
description: >-
  I'm an undergrad at UC Berkeley, studying Electrical Engineering and Computer Sciences (EECS). My background is in writing software, mathematics, AI, and robotics. In my free time, I enjoy exploring new topics in STEM, playing Go, card games, and listening to music.
baseurl: ""
url: "https://yashck.github.io/"
google_analytics: "G-W9NMDKRYXB"

collections:
  projects:
    permalink: /project/:name
    output: true
  achievements:
    permalink: /achievement/:name
    output: true

defaults:
  - scope:
      path: "_projects/*.md"
    values:
      layout: project
  - scope:
      path: "_achievements/*.md"
    values:
      layout: achievement

plugins:
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-minifier
  - jekyll-hostname
  - jekyll-hashsert

jekyll-minifier:
  exclude:
    - "sitemap.xml"
    - "assets/css/theme.css"
  uglifier_args:
    harmony: true

extlinks:
  attributes: { rel: nofollow noopener noreferrer, target: _blank }
  rel_include: [ ]
  rel_exclude: []

include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
